services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  flask:
    image: python:3.11
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    command: pm2-runtime start ecosystem.config.js
    ports:
      - "5050:5050"
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
