services:
  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5000"
    env_file:
      - ~/personal/env-cse/auth/.env

  video-api:
    container_name: video-api
    build:
      context: ./video
      dockerfile: Dockerfile
    ports:
      - "5001"
    depends_on:
      - redis
      - auth
      - minio
      - mongo
    env_file:
      - ~/personal/env-cse/video/.env

  transcoder:
    container_name: transcoder
    build:
      context: ./transcoder
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
      - mongo
      - minio
    env_file:
      - ~/personal/env-cse/transcoder/.env

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /tmp/minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - video-api
      - auth
    ports:
      - "80:80"
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/public/:/app/public/


volumes:
  videos:
  mongo_data:
