services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./confs:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html:rw
    environment:
      - DEFAULT_HOST=esk-pj-airplanes.cse356.compas.cs.stonybrook.edu
    labels:
      - "com.github.nginx-proxy.nginx"
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html:rw
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=patrick.muller.1@stonybrook.edu
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  flask:
    image: python:3.11
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    command: pm2-runtime start ecosystem.config.js
    ports:
      - "5050:5050"
      - "5555:5555"
    volumes:
      - ./server.py:/app/server.py
      - ./bp:/app/bp
      - ./templates:/app/templates
      - ./static:/app/static:rw
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=esk-pj-airplanes.cse356.compas.cs.stonybrook.edu
      - VIRTUAL_PORT=5050
      - LETSENCRYPT_HOST=esk-pj-airplanes.cse356.compas.cs.stonybrook.edu
      - LETSENCRYPT_EMAIL=patrick.muller.1@stonybrook.edu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  certs:
  html:
  acme:
