apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcoder
  template:
    metadata:
      labels:
        app: transcoder
    spec:
      containers:
        - name: transcoder
          image: us-east4-docker.pkg.dev/my-gcp-project-466212/video-app-repo/transcoder-app:latest
          envFrom:
            - secretRef:
                name: transcoder-secret
          imagePullPolicy: Always
