FROM python:3.10-slim

WORKDIR /app

# Install system dependencies including ffmpeg
RUN apt-get update && apt-get install -y --no-install-recommends \
  gcc \
  bash \
  libffi-dev \
  libssl-dev \
  curl \
  xz-utils \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \
  | tar -xJ --strip-components=1 -C /usr/local/bin

RUN mkdir -p /app/temp/videos

# Install Python dependencies
COPY requirements.txt .

RUN pip install -r requirements.txt

# Copy the rest of the app
COPY . .

# Run the Celery worker
CMD ["celery", "-A", "app", "worker", "--loglevel=info"]

