FROM nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./default.conf /etc/nginx/conf.d/default.conf

#  - ./nginx.conf:/etc/nginx/nginx.conf:ro
#  - ./nginx.tmpl:/etc/nginx/conf.d/default.conf:ro
# ports:
#  - "80:80"
#  - "443:443"

