# auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: us-east4-docker.pkg.dev/my-gcp-project-466212/video-app-repo/auth-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: auth-secret
