name: Docker Image CI

on:
  push:
    branches: [ "2025-refactor-main" ]
  pull_request:
    branches: [ "2025-refactor-main" ]
  workflow_dispatch: # <-- lets you run manually from the GitHub UI

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Build the Docker image
      run: |
          IMAGE_NAME=patrick42702/auth-video-app:$(date +%s)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build auth \
            --file auth/Dockerfile \
            --tag $IMAGE_NAME


    - name:
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: '$IMAGE_NAME'
        severity: 'CRITICAL'
