name: Docker Image CI

on:
  push:
    branches: [ "2025-refactor-main" ]
  pull_request:
    branches: [ "2025-refactor-main" ]
  workflow_dispatch: # <-- lets you run manually from the GitHub UI

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Detect which services changed
    - name: Detect changes
      id: changes
      run: |
        echo "AUTH_CHANGED=false" >> $GITHUB_ENV
        echo "TRANSCODER_CHANGED=false" >> $GITHUB_ENV
        echo "VIDEO_CHANGED=false" >> $GITHUB_ENV

        # Compare current commit with the base commit
        git fetch origin ${{ github.base_ref || github.ref_name }} --depth=1

        if git diff --name-only origin/${{ github.base_ref || github.ref_name }} HEAD | grep -q "^auth/"; then
          echo "AUTH_CHANGED=true" >> $GITHUB_ENV
        fi
        if git diff --name-only origin/${{ github.base_ref || github.ref_name }} HEAD | grep -q "^transcoder/"; then
          echo "TRANSCODER_CHANGED=true" >> $GITHUB_ENV
        fi
        if git diff --name-only origin/${{ github.base_ref || github.ref_name }} HEAD | grep -q "^video/"; then
          echo "VIDEO_CHANGED=true" >> $GITHUB_ENV
        fi

    # Build Auth if changed
    - name: Build auth image
      if: env.AUTH_CHANGED == 'true'
      run: |
        IMAGE_NAME=patrick42702/auth-video-app:auth-$(date +%s)
        echo "Building $IMAGE_NAME"
        docker build auth \
          --file auth/Dockerfile \
          --tag $IMAGE_NAME

    # Build Transcoder if changed
    - name: Build transcoder image
      if: env.TRANSCODER_CHANGED == 'true'
      run: |
        IMAGE_NAME=patrick42702/transcoder-video-app:transcoder-$(date +%s)
        echo "Building $IMAGE_NAME"
        docker build transcoder \
          --file transcoder/Dockerfile.prod \
          --tag $IMAGE_NAME

    # Build Video if changed
    - name: Build video image
      if: env.VIDEO_CHANGED == 'true'
      run: |
        IMAGE_NAME=patrick42702/video-api-video-app:video-$(date +%s)
        echo "Building $IMAGE_NAME"
        docker build video \
          --file video/Dockerfile.prod \
          --tag $IMAGE_NAME


    # - name: Build the Docker image
    #   run: |
    #       IMAGE_NAME=patrick42702/auth-video-app:$(date +%s)
    #       echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
    #       docker build auth \
    #         --file auth/Dockerfile \
    #         --tag $IMAGE_NAME


    - name:
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        severity: 'CRITICAL'
        exit-code: '1'

    - name: Log in to Docker Hub
      if: success()
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push image
      if: success()
      run: docker push ${{ env.IMAGE_NAME }}
